### ISSUE TITLE
Investigate support for 3.0

### ISSUE THREAD

**Issue by Dalmirog** [Dalmirog/OctoPosh#130]

**Comment by g0atcheez** [comment]
Hello. Loving this set of commands for working with Octo Deploy. Any update one when we might expect support for 3.0?

**Comment by Dalmirog** [comment]
Hi @g0atcheez ! Turns out it works for 3.0 just fine just the way it is now. This is thanks to the Octopus team not making any changes to the API itself.

Nice to hear you are liking it the module :)
