### ISSUE TITLE
UseBasicParsing missing on Invoke-WebRequest

### ISSUE THREAD

**Issue by blemasle** [Dalmirog/OctoPosh#144]
In `Get-OctopusProject.ps1`, `Invoke-WebRequest` is missing `-UseBasicParsing` argument. As a consequence, system account cannot use the script when Internet Explorer engine is not available/configured.

This is especially the case when running a script with a system account, as it is the case with a Teamcity agent for instance.

As all octopus endpoints return JSON, I guess DOM parsing is not use so `-UseBasicParsing` could be added on all `Invoke-WebRequest` inside OctoPosh.

**Comment by blemasle** [comment]
Any news on this pull request  ? Checks have failed because it seems that continuous integration has an issue with the build process, not the pull request itself

**Comment by mattcorr** [comment]
Is it possible to use `Invoke-RestMethod` instead of `Invoke-WebRequest`? I think it gets around that IE is not configured issue?

**Comment by blemasle** [comment]
@mattcorr I'm no Powershell expert. As requested by @Dalmirog on #145 I'll send another pull request with my fix. Feel free to submit your own fix :)
