### ISSUE TITLE
Make GET cmdlets less whiny when they can't find a result

### ISSUE THREAD

**Issue by Dalmirog** [Dalmirog/OctoPosh#173]
## _The following will be applied to all `GET` commands in the module_

If you run `Get-OctopusProject -Name "ProjectThatDoesNotExist"` you'll get an error saying

```
Get-OctopusProject : Project not found: ProjectThatDoesNotExist
At line:1 char:1
+ Get-OctopusProject -ProjectName ProjectThatDoesNotExist -Verbose
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorExcep 
   tion
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorExceptio 
   n,Get-OctopusProject
```

This could get even nastier if you pass multiple resource names and it can't find more than one of them.

Instead, I'm gonna change the cmdlets to just return nothing if they can't find a specific resource.

If you wanna know what happened in the background, you can always run the cmdlet with `-verbose` to get more info like this:

``` Powershell
PS C:\> Get-OctopusProject -ProjectName ProjecThatDoesNotExist -Verbose
VERBOSE: [Get-OctopusProject] Filtering projects by name: ProjecThatDoesNotExist
VERBOSE: [Get-OctopusProject] Project not found: ProjecThatDoesNotExist
VERBOSE: [Get-OctopusProject] Projects found: 0
```

When you pass 1 project that exists and another that doesn't

``` Powershell
PS C:\> Get-OctopusProject -ProjectName ProjecThatDoesNotExist,ProjectThatExists -Verbose
VERBOSE: [Get-OctopusProject] Filtering projects by name: ProjecThatDoesNotExist
 ProjectThatExists
VERBOSE: [Get-OctopusProject] Project not found: ProjecThatDoesNotExist
VERBOSE: [Get-OctopusProject] Projects found: 1
VERBOSE: [Get-OctopusProject] Getting info from project ProjectThatExists
```
### Progress tracker
- [ ] Get-OctopusConnectionInfo
- [ ] Get-OctopusDeployment
- [ ] Get-OctopusEnvironment
- [ ] Get-OctopusFeed
- [ ] Get-OctopusLifeCycle
- [ ] Get-OctopusMachine
- [ ] Get-OctopusMaintenanceMode
- [x] Get-OctopusProject
- [ ] Get-OctopusProjectGroup
- [ ] Get-OctopusRelease
- [ ] Get-OctopusResourceModel
- [ ] Get-OctopusSMTPConfig
- [ ] Get-OctopusTask
- [ ] Get-OctopusTeam
- [ ] Get-OctopusUser
- [ ] Get-OctopusUserRole
- [ ] Get-OctopusVariableSet

**Comment by mattcorr** [comment]
Will the `-ErrorAction Stop` still work?

**Comment by Dalmirog** [comment]
@mattcorr how are you using `-erroraction stop` currently?

**Comment by mattcorr** [comment]
for error checking when users pass in names of environments as parameters on scripts.

ie:

```
$environment = Get-OctopusEnvironment -EnvironmentName $EnvironmentName -ErrorAction Stop

<do more stuff here>
```

So if they have an invalid Environment, it will stop on the `Get-OctopusEnvironment` command.

Is there a better way?

**Comment by Dalmirog** [comment]
@mattcorr I need to think about this one a bit more. Gonna move it to milestone `0.6` for now.
