### ISSUE TITLE
Create cmdlet to get the Octopus dashboard

### ISSUE THREAD

**Issue by Dalmirog** [Dalmirog/OctoPosh#178]
It'll only show the data retrieved from the `/api/dashboard`. Here's an example of what you can get from that call [JSON example](https://gist.github.com/Dalmirog/5edd0ca1235e68035043e57c9e5e5a94)

- What columns you'd like to see on the output of the cmdlet?
- Which Parameters/filters you'd like to see? The cmdlet will always bring the whole dashboard JSON, as there's no way to filter that down from the API. So any filtering/massaging will be applied locally in PS

**Comment by mattcorr** [comment]
Hmm would like to see filtering by Environment Name?

ie.. show me the apps that are currently installed in "UAT" environment?

But yeah the Dashboard does return a **lot** of stuff so its hard to know for sure what columns to add that are not already there?

**Comment by mattcorr** [comment]
I have since noticed that the call to `Get-OctopusEnvironment` already returns a **lot** of stuff that is found on the Dashboard _(provided you don't provide the `-ResourceOnly` parameter)_. I would assume the priority for this is not high unless many others are asking for it?
