### ISSUE TITLE
Error in documentation for Block-OctopusRelease

### ISSUE THREAD

**Issue by fatmanmclone90** [Dalmirog/OctoPosh#179]
The example given for Block-OctopusRelease is incorrect.  The example given is:
`PS C:\>Get-OctopusRelease -Project "MyProduct.Webapp" -version 1.0.1 | Block-OctopusRelease -Reason "Because of reasons"`

It should be:
`PS C:\>Get-OctopusRelease -Project "MyProduct.Webapp" -version 1.0.1 | Block-OctopusRelease -Description "Because of reasons"`

**Comment by Dalmirog** [comment]
Fixed. Thanks for the heads up!
