### ISSUE TITLE
Bundle Octo.exe with Octoposh

### ISSUE THREAD

**Issue by Dalmirog** [Dalmirog/OctoPosh#183]
See approach -> https://github.com/Dalmirog/OctoPosh/issues/183#issuecomment-289551980

**Comment by mattcorr** [comment]
Can I ask why this is needed? does Octo.exe do stuff the REST API can't?

**Comment by beaudryj** [comment]
i don't really understand the point if you already have the DLLs included and the DLLs and Rest API already offer more than the .exe

**Comment by Dalmirog** [comment]
The idea of Octoposh being a PS module for Octopus that doesn't give you a way to start a deployment makes me sad. With that idea in mind, the obvious thought was "Hey I should totally create cmdlets to create releases/deployments using the API" so I created #100.

As soon as I started planning those cmdlets in my head, I realized I was basically re-writing Octo.exe in Powershell, which doesn't make a lot of sense. The Octopus team has put [**a lot** of effort into `Octo.exe` through the years](https://github.com/OctopusDeploy/Issues/issues?page=1&q=octo.exe&utf8=%E2%9C%93), and there was no way I could write something better than them. To answer to your questions, there's nothing `Octo.exe` can do that the API can't. Basically cause `Octo.exe` is just a smart wrap around the API. A very smart wrap supported by an entire team of amazing devs :)

The 2nd idea that came to my mind was "Lets bundle Octo.exe with Octoposh". Of course, just bundling a fixed version of `Octo.exe` would force me to keep releasing new versions of Octoposh every time an important fix was submitted to `Octo.exe`, which is also a lot of trouble.

So the current plan is

- Add a cmdlet that lets you download a specific version of `Octo.exe` or the latest one.
- This cmdlet would also create a variable that would always point to the path where `Octo.exe` was doenloaded, so users could to `& $env:OctoExe create-release`
- Add another cmdlet that allows you to check which versions of `Octo.exe` you have downloaded, and to which is this Octo.exe variable pointing to.

Would love to hear your thoughts about this.

**Comment by mattcorr** [comment]
At the moment I am using OctoPosh to replace my current common library that I had created last year. Your code has pretty much replaced all function except for one:

```
function Create-Deployment($EnvironmentId, $ProjectId, $ReleaseId) 
{
    $newDeployment = @{ EnvironmentId = $EnvironmentId
                        ProjectId = $ProjectId
                        ReleaseId = $ReleaseId
                      }
    $body = $newDeployment | ConvertTo-Json
    
    return Invoke-RestMethod -Method Post  -Uri "$($env:OctopusURL)/api/deployments" -Body $body -Headers @{"X-Octopus-ApiKey"=$env:OctopusAPIKey}
}
```

Obviously the above function has some assumptions like the Release is already created.. etc.

I don't know as much about the inner workings of Octopus binaries as you of course, but I am uncertain how calling the REST API would be considered re-writing `Octo.exe`? Its just another path to get to the same functionality deep down right?

I am a bit on the fence between PowerShell functions calling an executable or just calling REST APIs and dealing with the objects via PowerShell.  Its up to you how "pure" you want to the scripting to be. My previous approach was pretty much 100% powershell scripts and only calling executable when there was no other options. I could be persuaded if calling the executable is a more viable option! :)

My thoughts at the moment anyway. Keep up the great work!

**Comment by Dalmirog** [comment]
That functions definitely gets the job done, but like you very well mentioned @mattcorr , it relies on too many assumptions and offers very little flexibility.

Octo.exe does things like:

- Check if the release exists, and if not it creates it.
- Check if the environment exists before starting a deployment on it.
- Check if you should be able to deploy to that environment.
- Offers a way to decide which version of each package you want to use in the deployment.
- **plenty** other things related to releases/deployments

At the same time, in the latest versions Octo.exe has gained support to [**Create Packages**](http://docs.octopusdeploy.com/display/OD/Using+Octo.exe) and [**Push them to repositories**](http://docs.octopusdeploy.com/display/OD/Pushing+packages)

All of these are features I'd like to introduce to Octoposh to make it the `Go-to cmd line toolkit for Octopus`. But like I said, they are already in `Octo.exe` and re-writing them in Powershell makes very little sense. I'd rather focus on coding things that are not in `Octo.exe`, like cmdlets to create/delete resources and `Get` cmdlets with good enough filters that return objects and not plain text (like octo) so you can play around with them chaining them with other commands.

**Comment by beaudryj** [comment]
Why do they keep building on the .exe when they could work with you to
build stronger web APIs and wrap the dlls?

**Comment by matt-richardson** [comment]
@beaudryj - all of Octopus is based on web api's. Everything octo.exe does is via the REST api.

**Comment by Dalmirog** [comment]
Just like @matt-richardson  said, the DLLs that `Octo.exe` uses simply call the REST api.

@beaudryj for the moment that's not in our plans. Octoposh is still a project I maintain in my free time. But who knows? Perhaps the module becomes amazingly popular one day and we might consider making it *a bit* more official :)

**Comment by mud5150** [comment]
Why not use chocolatey or nuget to pull down the dependencies. This would cover updating the octo client library and the octo.exe.

**Comment by Dalmirog** [comment]
Hi @mud5150 . I'm currently working on a prototype that downloads `Octo.exe` using Nuget or Chocolatey (still haven't decided whcih I'm gonna use). I'm planning on shipping the first version with 0.6.2/1.0.0-Beta2

**Comment by beaudryj** [comment]
Why not just make a flag and give the option or it does a check to see
what's installed and use whatever is installed, if neither prompt to
install

**Comment by Dalmirog** [comment]
Hi @beaudryj I'm currently working in a model that goes a bit like this:

*The entire point of the cmdlets and variables below is for the user to have a simple and stress-free way to execute `Octo.exe` regardless of where their prompt is on.*

Octoposh would introduce 2 new environment variables and a couple new cmdlets:

- `$Env:OctopusToolsFolder`. This variable will point to a folder that has child folders with versions of Octo.exe
- `$env:Octoexe`. This var will point to the current default `Octo.exe` version. The goal is that you can do `& $env:Octoexe create-release -bla -bla` from anywhere in your prompt.

- `Set-OctopusToolsFolder`. Will set the value of `$env:OctopusToolsFolder`
- `Get-OctopusToolsFolder`. Will get the value of `$env:OctopusToolsFolder`

- `Set-OctopusToolPath`. Will set the value of `$env:Octoexe`
- `Get-OctopusToolPath`. Will get the value of `$env:Octoexe`

- `Install-OctopusTool`. Will download a given version of `Octo.exe` from Nuget/Chocolatey (still haven decided) to the path in `$env:OctopusToolsFolder`

- `UnInstall-OctopusTool`. Will help cleaning up unnecesary versios of `Octo.exe` lying around in `$env:OctopusToolsFolder`. It'll have a parameter called `-keepLatest` so you can just keep the most recent version of `Octo.exe`

Would love to hear some thoughts on this.

**Comment by beaudryj** [comment]
Cool Stuff, do you plan on creating commandlets that invoke-octo.exe and pass parameters? if so how do you plan on handling the output for errors ?

**Comment by Dalmirog** [comment]
@beaudryj actually I do not plan on doing that. All the module will do is:

1) Make it easier for the user to download `Octo.exe`
2) Point `$env:Octoexe` to the path of an `Octo.exe` copy, so you can easily invoke it like this:

```Powershell
& $env:OctoExe create-release --server http://server.com --apikey API-1234567 --Project MyProject
```

Creating cmdlets to wrap around `Octo.exe` would introduce a bit of unnecessary overhead IMO. If the Octopus team adds a parameter or a new command, **Octoposh** users would have to wait until a new release is out that supports these changes in `Octo.exe`. With the approach I'm proposing all they'll have to do is run `Install-OctopusTool -Latest -SetAsDefault` and they'll get the latest version from Nuget ready to go.

I guess I could add something like: 

```Powershell
Invoke-OctoExe -parameters "create-release --server http://server.com --apikey API-1234567 --Project MyProject"
```

It wouldn't do *anything* more than invoking `Octo.exe` using the string passed to `-parameters` as parameters, but it would at least improve the discovery of the functionality:

New user downloads Octoposh -> Runs `get-commands -module Octoposh` -> Notices a cmdlet called `invoke-Octoexe` and says "Oh there's a cmdlet for that!" -> Tries to run it without having ran `Install-OctopusTool` in the first place -> Gets a nice error that tells him what to do and points to documentation on how to get started.

**Comment by dragon788** [comment]
I'm liking where you are going with this. I'm partial to Chocolatey as the Octo.exe distribution method (just love the easy package management and ability to create your own if the gallery doesn't meet your needs), and at one point they were syncing some of the Nuget gallery over as a service to their users, not sure if that is still happening or if a change on the Nuget side broke something. I'm guessing eventually OneGet will work with Nuget or Chocolatey so for Windows 10 (or PowerShell 5.x) and up it will be much easier to install packages no matter the source.

**Comment by Dalmirog** [comment]
@dragon788 I ended up going with `Nuget.org` and using the `Nuget` api to download `Octo.exe` like this: http://blog.nuget.org/20130520/Play-with-packages.html

It should be fairly transparent to the user that way :)

Full walkthrough of the new feature here: https://github.com/Dalmirog/OctoPosh/wiki/Running-deployments-with-Octoposh
