### ISSUE TITLE
Modify Resources - Put all of a (single) Project's variables into a New Library Variable Set - Incorrect code in example

### ISSUE THREAD

**Issue by dnmel0** [Dalmirog/OctoPosh#204]
The example at this [link](https://github.com/Dalmirog/OctoPosh/wiki/Modifying-Resources#put-all-of-a-single-projects-variables-into-a-new-library-variable-set) is incorrect: 

It shows this:

```
#Save the set to the Octopus Database
New-OctopusResource -Resource $NewVariableSet>
```

but it should be **$NewLibraryVariableSetObject** :

```
#Save the set to the Octopus Database
New-OctopusResource -Resource $NewLibraryVariableSetObject
```

**Comment by gabe1314** [comment]
Thank you!
