### ISSUE TITLE
Any plans to add support for tenants?

### ISSUE THREAD

**Issue by erichexter** [Dalmirog/OctoPosh#206]
want a pull request?

**Comment by mud5150** [comment]
I'm looking at using this module and also need tenant support. @erichexter do you already have something written? I didn't see a fork.

**Comment by erichexter** [comment]
I ​extended some existing code using the octo client. But will need the
tenant support eventually.

**Comment by mud5150** [comment]
@erichexter  I need to add tenant support as well. For us the primary purpose will be to bulk add tenants and tags. What functionality are you looking for? Perhaps we can work on this together to get everything we need. I haven't really used this module before so I'm just starting to look over it so I can follow the existing patterns.

**Comment by mud5150** [comment]
@Dalmirog I'd like to take a whack at adding tenant features to the module. Would that be ok with you? I was looking through the pester tests. Can you give me some advice on how you have your test environment configured to make these work? Are you using the octopus azure image? Would be cool to get the entire test environment wrapped in an ARM template.

**Comment by erichexter** [comment]
@mud5150  I basically want to create tenants and add them to a project/environement as part of our onboarding process. While we dont have a usecase for tags yet. I see us using it in the near future.

**Comment by mud5150** [comment]
@erichexter Sounds good. I forked it to my account so feel free to keep an eye on it. Looking through the module now. Hopefully I'll have something to show tomorrow.

**Comment by Dalmirog** [comment]
Hi @erichexter . I've added support for this in `0.6.0`. Please reach out in the [Gitter channel](https://gitter.im/Dalmirog/OctoPosh#initial) if you have questions about the usage and I'll jump in to give you a hand.

**Comment by erichexter** [comment]
great, thanks for the follow up.
