### ISSUE TITLE
Better error handling for bad connection info

### ISSUE THREAD

**Issue by mud5150** [Dalmirog/OctoPosh#207]
Should handle these with a friendly error. Here is an example of what you might get currently if the url is set wrong. 

PS> Get-OctopusMachine
Exception calling "FindAll" with "0" argument(s): "Unable to process response from server: Unexpected character
encountered while parsing value: <. Path '', line 0, position 0.. Response content: <!DOCTYPE html>
<html lang="en">
<head>
  <title ng-bind="$root.pageTitle + ' - Octopus Deploy'">"
At C:\Users\mfrank\Documents\WindowsPowerShell\Modules\octoposh\0.5.1\scripts\Get-OctopusMachine.ps1:135 char:13
-             $Machines = $c.repository.Machines.FindAll()
-             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
  - FullyQualifiedErrorId : OctopusDeserializationException

**Comment by mansarik** [comment]
Any update on the above... i am stuck at the same place.
