### ISSUE TITLE
Get-OctopusDeployment doesn't return package names

### ISSUE THREAD

**Issue by sqldan** [Dalmirog/OctoPosh#219]
Get-OctopusDeployment doesn't return the package name.  Just the version.  Example output:
  "Package             : {@{Name=; Version=20160909.6}, @{Name=; Version=20160909.6}}"

At about line 131 of Get-OctopusDeployment (14ac53c) you’ll find
    Name = $ds.Actions.properties.'Octopus.Action.Package.NuGetPackageId'.value 

However 'Octopus.Action.Package.NuGetPackageId' doesn't seem to be what the package ID is called.  If I change the above to:
    Name = $ds.Actions.properties.'Octopus.Action.Package.PackageId'.value

It then works.  To test I just created a function called Get-OctopusDeployment2 with that on amendment and it returned the packageIds.

**Comment by Dalmirog** [comment]
Hi there! I just released `0.6.0` which should fix this issue. Before you download it please take a read at #234 , specially at the list of missing cmdlets
