### ISSUE TITLE
Create Get-OctopusEnvironment

### ISSUE THREAD

**Issue by Dalmirog** [Dalmirog/OctoPosh#23]

**Comment by Swoogan** [comment]
Hello,

I am also working on a suite of Octopus Deploy cmdlets. It seems as though we don't yet have much overlap, but I see your list of enhancements includes a lot of the things my project already does. I am wondering if we could somehow collaborate and prevent duplication of work?

My cmdlets are written in C#. Right now I'm focusing on basic CRUD type operations: Get, Add, Remove, and Update. After that I was intending to add some more advanced cmdlets, written in PowerShell, to build off of the basic ones and glue several cmdlets together.

Let me know if you're interested in working together. https://github.com/Swoogan/Octopus-Cmdlets


Colin
