### ISSUE TITLE
Update or remove releases from Github

### ISSUE THREAD

**Issue by davestephens** [Dalmirog/OctoPosh#305]
The releases on Github are way behind what's actually available for the module. 

I'd like to suggest removing them altogether or updating to the latest versions as new ones are released.

Thanks in advance!

**Comment by Dalmirog** [comment]
The actual releases are being pushed to the (Powershell Gallery)[powershellgallery.com/packages/Octoposh/] so yeah, there's really no use for them as github releases.

I went ahead and deleted all of them.

Thanks for the heads up @davestephens :)
