### ISSUE TITLE
Get-OctopusProject cannot get a particular project

### ISSUE THREAD

**Issue by mwoffenden** [Dalmirog/OctoPosh#319]
Get-OctopusProject cannot get a particular project (named "Build"), and in fact throws this error:

```
Get-OctopusProject : Object reference not set to an instance of an object.
At line:1 char:1
+ Get-OctopusProject -name "Build"
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-OctopusProject], NullReferenceException
    + FullyQualifiedErrorId : System.NullReferenceException,Octoposh.Cmdlets.GetOctopusProject
```

The project exists in the database and could be found before using the same command.  All other projects can be found using the same command.

How do we debug this?

**Comment by webmastir** [comment]
It seems to work fine for me. I even created a test group named "Build".

```
PS> Get-OctopusProject -name "Build"

Name              : Build
Id                : Projects-302
ProjectGroupName  : Testgroup
LifecycleName     : Default Lifecycle
LatestDeployments : {}
AutoCreateRelease : False
Resource          : Octopus.Client.Model.ProjectResource
```
What version of Octopus and OctoPosh are you using?

**Comment by mwoffenden** [comment]
Thanks for your reply, webmastir.

Yes, it worked for us before as well.  But we changed one of the related environments, which apparently broke something in the cmdlet.

Never mind however, we have re-written the affected code using the client API and that works perfectly.
